import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{BrowserRouter,useNavigate,useLocation,Routes,Route,Link}from"react-router-dom";
import*as I from"lucide-react";
import QRCode from"qrcode";
import"./styles.css";

const TOOLS=[
{id:"password",name:"Gerador de Senhas",desc:"Crie senhas fortes e aleatórias.",icon:"KeyRound"},
{id:"units",name:"Conversor de Unidades",desc:"Converta comprimento, peso e mais.",icon:"ArrowLeftRight"},
{id:"counter",name:"Caracteres / Palavras",desc:"Conte texto em tempo real.",icon:"Type"},
{id:"qr",name:"Gerador de QR Code",desc:"Transforme texto ou links em QR.",icon:"QrCode"},
{id:"timer",name:"Cronômetro e Timer",desc:"Controle seu tempo com precisão.",icon:"Timer"},
{id:"notes",name:"Bloco de Notas Rápido",desc:"Crie notas salvas neste dispositivo.",icon:"StickyNote"},
{id:"calc",name:"Calculadora Científica",desc:"Cálculos simples e avançados.",icon:"Calculator"},
{id:"colors",name:"Gerador de Cores",desc:"Crie paletas e copie seus códigos.",icon:"Palette"},
{id:"currency",name:"Conversor de Moedas",desc:"Converta valores com taxas editáveis.",icon:"Coins"},
{id:"text",name:"Ferramenta de Texto",desc:"Transforme e limpe textos.",icon:"TextCursorInput"},
{id:"video",name:"Tocador de Vídeo",desc:"Reproduza vídeos por URL ou arquivo.",icon:"Video"},
{id:"audio",name:"Leitor de Áudio",desc:"Player completo para seus áudios.",icon:"Headphones"}
];
const map=Object.fromEntries(TOOLS.map(x=>[x.id,x]));
function Icon({name,size=21}){let C=I[name]||I.Sparkles;return <C size={size}/>}

function useLocal(key,fallback){const[v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return[v,setV]}

function Layout({children}){const[dark,setDark]=useState(()=>localStorage.theme==="dark");useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.theme=dark?"dark":"light"},[dark]);return <div className="app">
<header><Link to="/" className="brand"><span className="brandMark"><Icon name="Sparkles"/></span>Trinkets</Link><nav><Link to="/">Início</Link><Link to="/about">Sobre</Link></nav><button className="iconBtn" onClick={()=>setDark(v=>!v)} aria-label="Alternar tema">{dark?<Icon name="Sun"/>:<Icon name="Moon"/>}</button></header>
<main>{children}</main><footer>Trinkets · suas bugigangas digitais em um só lugar</footer></div>}

function Back(){const nav=useNavigate();return <button className="back" onClick={()=>nav("/")}><Icon name="ArrowLeft" size={18}/> Voltar para Trinkets</button>}
function Page({id,children}){let t=map[id];return <section className="toolPage"><Back/><div className="toolHead"><div className="toolIcon"><Icon name={t.icon} size={25}/></div><div><h1>{t.name}</h1><p>{t.desc}</p></div></div>{children}</section>}
function Home(){const[q,setQ]=useState("");const[favs,setFavs]=useLocal("trinkets:favs",[]);let list=TOOLS.filter(t=>(t.name+" "+t.desc).toLowerCase().includes(q.toLowerCase()));let favorite=TOOLS.filter(t=>favs.includes(t.id));return <><section className="hero"><div className="eyebrow"><Icon name="Sparkles" size={14}/> caixa de ferramentas digitais</div><h1>Trinkets</h1><p>Suas bugigangas digitais em um só lugar</p><div className="search"><Icon name="Search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar uma bugiganga..."/></div></section>{favorite.length>0&&<ToolGrid title="Favoritos" tools={favorite} favs={favs} setFavs={setFavs}/>}<ToolGrid title="Todas as bugigangas" tools={list} favs={favs} setFavs={setFavs}/></>}
function ToolGrid({title,tools,favs,setFavs}){return <section className="section"><div className="sectionTitle"><h2>{title}</h2><span>{tools.length}</span></div><div className="grid">{tools.map(t=><Link to={"/tool/"+t.id} className="card" key={t.id}><button className={"fav "+(favs.includes(t.id)?"on":"")} onClick={e=>{e.preventDefault();setFavs(favs.includes(t.id)?favs.filter(x=>x!==t.id):[...favs,t.id])}}><Icon name="Star" size={17}/></button><div className="cardIcon"><Icon name={t.icon}/></div><h3>{t.name}</h3><p>{t.desc}</p><span className="open">Abrir <Icon name="ArrowUpRight" size={15}/></span></Link>)}</div></section>}

function Password(){const[len,setLen]=useState(18),[o,setO]=useState({l:true,u:true,n:true,s:true}),[pwd,setPwd]=useState("");function gen(){let chars=(o.l?"abcdefghijklmnopqrstuvwxyz":"")+(o.u?"ABCDEFGHIJKLMNOPQRSTUVWXYZ":"")+(o.n?"0123456789":"")+(o.s?"!@#$%^&*()-_=+[]{}?":"");if(!chars)return setPwd("");let a=Array.from({length:len},()=>chars[Math.floor(Math.random()*chars.length)]);setPwd(a.join(""))}useEffect(gen,[len,o]);return <Page id="password"><div className="panel"><div className="passwordBox"><span>{pwd||"Selecione ao menos um tipo"}</span><button className="copy" onClick={()=>navigator.clipboard.writeText(pwd)}><Icon name="Copy"/> Copiar</button></div><label>Tamanho <b>{len}</b><input type="range" min="6" max="64" value={len} onChange={e=>setLen(+e.target.value)}/></label><div className="checks">{[["l","Minúsculas"],["u","Maiúsculas"],["n","Números"],["s","Símbolos"]].map(([k,v])=><label key={k}><input type="checkbox" checked={o[k]} onChange={()=>setO({...o,[k]:!o[k]})}/>{v}</label>)}</div><button className="primary" onClick={gen}><Icon name="RefreshCw"/> Gerar nova senha</button></div></Page>}

const units={Comprimento:{m:1,km:1000,cm:.01,mm:.001,mi:1609.344,ft:.3048},Peso:{kg:1,g:.001,lb:.453592},Volume:{L:1,ml:.001,m3:1000,gal:3.78541},Dados:{B:1,KB:1024,MB:1048576,GB:1073741824}};
function Units(){const[cat,setCat]=useState("Comprimento"),[v,setV]=useState(1),[from,setFrom]=useState("m"),[to,setTo]=useState("km");let opts=cat==="Temperatura"?["°C","°F","K"]:Object.keys(units[cat]);useEffect(()=>{setFrom(opts[0]);setTo(opts[1]||opts[0])},[cat]);let out;if(cat==="Temperatura"){let c=from==="°C"?+v:from==="°F"?((+v-32)*5/9):+v-273.15;out=to==="°C"?c:to==="°F"?c*9/5+32:c+273.15}else out=(+v*units[cat][from])/units[cat][to];return <Page id="units"><div className="panel"><select value={cat} onChange={e=>setCat(e.target.value)}><option>Comprimento</option><option>Peso</option><option>Temperatura</option><option>Volume</option><option>Dados</option></select><input className="bigInput" type="number" value={v} onChange={e=>setV(e.target.value)}/><div className="two"><select value={from} onChange={e=>setFrom(e.target.value)}>{opts.map(x=><option key={x}>{x}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}>{opts.map(x=><option key={x}>{x}</option>)}</select></div><div className="result">{Number(out).toLocaleString("pt-BR",{maximumFractionDigits:8})} <small>{to}</small></div></div></Page>}

function Counter(){const[t,setT]=useState("");let words=t.trim()?t.trim().split(/\s+/).length:0,lines=t?t.split("\n").length:0;return <Page id="counter"><div className="panel"><textarea rows="12" value={t} onChange={e=>setT(e.target.value)} placeholder="Cole ou digite seu texto..."/><div className="stats"><Stat n={t.length} l="Caracteres"/><Stat n={words} l="Palavras"/><Stat n={lines} l="Linhas"/><Stat n={Math.max(1,Math.ceil(words/200))+" min"} l="Leitura"/></div></div></Page>}
function Stat({n,l}){return <div><b>{n}</b><span>{l}</span></div>}

function QR(){const[v,setV]=useState("https://example.com"),[src,setSrc]=useState("");useEffect(()=>{QRCode.toDataURL(v||" ",{width:420,margin:2}).then(setSrc)},[v]);return <Page id="qr"><div className="panel qrPanel"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Digite um texto ou URL"/>{src&&<img className="qr" src={src}/>}<a className="primary center" href={src} download="trinkets-qrcode.png"><Icon name="Download"/> Baixar QR Code</a></div></Page>}

function Timer(){const[mode,setMode]=useState("up"),[running,setRunning]=useState(false),[sec,setSec]=useState(0),[minutes,setMinutes]=useState(1);useEffect(()=>{if(!running)return;let id=setInterval(()=>setSec(s=>{if(mode==="down"&&s<=1){setRunning(false);beep();return 0}return s+(mode==="down"?-1:1)}),1000);return()=>clearInterval(id)},[running,mode]);function beep(){try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.value=.08;o.start();o.stop(a.currentTime+.25)}catch{}}return <Page id="timer"><div className="panel timer"><div className="tabs"><button className={mode==="up"?"sel":""} onClick={()=>{setMode("up");setSec(0);setRunning(false)}}>Cronômetro</button><button className={mode==="down"?"sel":""} onClick={()=>{setMode("down");setSec(minutes*60);setRunning(false)}}>Timer</button></div><div className="clock">{fmt(sec)}</div>{mode==="down"&&<input type="number" min="1" value={minutes} onChange={e=>{setMinutes(+e.target.value);if(!running)setSec(+e.target.value*60)}}/>}<div className="actions"><button className="primary" onClick={()=>setRunning(!running)}><Icon name={running?"Pause":"Play"}/>{running?"Pausar":"Iniciar"}</button><button onClick={()=>{setRunning(false);setSec(mode==="down"?minutes*60:0)}}><Icon name="RotateCcw"/> Resetar</button></div></div></Page>}
function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}

function Notes(){const[notes,setNotes]=useLocal("trinkets:notes",[]),[sel,setSel]=useState(null);function save(){if(!sel)return;let n=sel.id?notes.map(x=>x.id===sel.id?sel:x):[...notes,{...sel,id:Date.now()}];setNotes(n);setSel(null)}function del(id){setNotes(notes.filter(x=>x.id!==id));setSel(null)}return <Page id="notes"><div className="notes"><aside><button className="primary" onClick={()=>setSel({title:"",body:""})}><Icon name="Plus"/> Nova nota</button>{notes.map(n=><button className="noteItem" key={n.id} onClick={()=>setSel(n)}><b>{n.title||"Sem título"}</b><span>{n.body.slice(0,50)}</span></button>)}</aside><div className="panel noteEditor">{sel?<><input placeholder="Título" value={sel.title} onChange={e=>setSel({...sel,title:e.target.value})}/><textarea value={sel.body} onChange={e=>setSel({...sel,body:e.target.value})} placeholder="Escreva sua nota..."/><div className="actions"><button className="primary" onClick={save}>Salvar</button>{sel.id&&<button onClick={()=>del(sel.id)}>Apagar</button>}</div></>:<div className="empty"><Icon name="StickyNote"/><p>Crie ou selecione uma nota.</p></div>}</div></div></Page>}

function Calc(){const[e,setE]=useState("");function add(x){setE(v=>v+x)}function equal(){try{let x=e.replace(/×/g,"*").replace(/÷/g,"/").replace(/√/g,"Math.sqrt");setE(String(Function("return "+x)()))}catch{setE("Erro")}}let keys=["sin(","cos(","tan(","√(","7","8","9","÷","4","5","6","×","1","2","3","-","0",".","(",")","+","C","⌫","="];return <Page id="calc"><div className="calc"><input value={e} readOnly/><div className="keys">{keys.map(k=><button key={k} onClick={()=>k==="="?equal():k==="C"?setE(""):k==="⌫"?setE(v=>v.slice(0,-1)):add(k)}>{k}</button>)}</div></div></Page>}

function Colors(){const[base,setBase]=useState("#6d5dfc");let n=parseInt(base.slice(1),16),r=n>>16,g=n>>8&255,b=n&255,colors=[-45,-22,0,22,45].map(d=>"#"+[r,g,b].map(x=>Math.max(0,Math.min(255,x+d)).toString(16).padStart(2,"0")).join(""));return <Page id="colors"><div className="panel"><div className="colorPick"><input type="color" value={base} onChange={e=>setBase(e.target.value)}/><input value={base} onChange={e=>setBase(e.target.value)}/></div><div className="palette">{colors.map(c=><button key={c} style={{background:c}} onClick={()=>navigator.clipboard.writeText(c)}><span>{c}</span></button>)}</div></div></Page>}

function Currency(){const rates={BRL:1,USD:.18,EUR:.17,GBP:.15};const[v,setV]=useState(100),[a,setA]=useState("BRL"),[b,setB]=useState("USD");let out=(+v/rates[a]*rates[b]).toFixed(2);return <Page id="currency"><div className="panel"><div className="two"><input type="number" value={v} onChange={e=>setV(e.target.value)}/><select value={a} onChange={e=>setA(e.target.value)}>{Object.keys(rates).map(x=><option key={x}>{x}</option>)}</select></div><div className="two"><select value={b} onChange={e=>setB(e.target.value)}>{Object.keys(rates).map(x=><option key={x}>{x}</option>)}</select><input value={out} readOnly/></div><p className="hint">Taxas demonstrativas. Para produção, conecte uma API de câmbio.</p></div></Page>}

function TextTool(){const[t,setT]=useState("");let words=t.trim()?t.trim().split(/\s+/).length:0;return <Page id="text"><div className="panel"><textarea rows="12" value={t} onChange={e=>setT(e.target.value)} placeholder="Digite seu texto..."/><div className="actions wrap"><button onClick={()=>setT(t.toUpperCase())}>MAIÚSCULAS</button><button onClick={()=>setT(t.toLowerCase())}>minúsculas</button><button onClick={()=>setT(t.normalize("NFD").replace(/[\u0300-\u036f]/g,""))}>Remover acentos</button><button onClick={()=>navigator.clipboard.writeText(t)}><Icon name="Copy"/> Copiar</button></div><div className="stats"><Stat n={t.length} l="Caracteres"/><Stat n={words} l="Palavras"/></div></div></Page>}

function Media({audio=false}){const[url,setUrl]=useState(""),[src,setSrc]=useState(""),[volume,setVolume]=useState(80),[rate,setRate]=useState(1),ref=useRef();function local(e){let f=e.target.files?.[0];if(f)setSrc(URL.createObjectURL(f))}function seek(d){if(ref.current)ref.current.currentTime=Math.max(0,ref.current.currentTime+d)}return <Page id={audio?"audio":"video"}><div className="panel media"><div className="mediaInput"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder={audio?"URL MP3/WAV/OGG":"URL direta de vídeo .mp4/.webm"}/><button className="primary" onClick={()=>setSrc(url)}>Carregar</button></div><label className="upload">Ou escolher arquivo <input type="file" accept={audio?"audio/*":"video/*"} onChange={local}/></label>{src&&(audio?<audio ref={ref} src={src} controls/>:<video ref={ref} src={src} controls playsInline/>)}{src&&<><div className="mediaRow"><button onClick={()=>seek(-10)}>↶ 10s</button><button onClick={()=>seek(10)}>10s ↷</button>{audio&&<select value={rate} onChange={e=>{let x=+e.target.value;setRate(x);ref.current.playbackRate=x}}>{[.5,.75,1,1.25,1.5,2].map(x=><option key={x}>{x}x</option>)}</select>}<button onClick={()=>ref.current&&(ref.current.muted=!ref.current.muted)}><Icon name="Volume2"/> Mute</button></div><label>Volume <b>{volume}%</b><input type="range" min="0" max="100" value={volume} onChange={e=>{let x=+e.target.value;setVolume(x);if(ref.current)ref.current.volume=x/100}}/></label></>}</div></Page>}

function About(){return <section className="about"><div className="eyebrow"><Icon name="Sparkles" size={14}/> sobre o projeto</div><h1>Uma caixa de ferramentas para pequenas tarefas.</h1><p>Trinkets reúne mini-aplicativos rápidos em uma interface única. Abra, use e volte — sem menus complicados.</p><div className="aboutGrid"><div><Icon name="Zap"/><h3>Rápido</h3><p>Uma ferramenta para cada pequena tarefa.</p></div><div><Icon name="ShieldCheck"/><h3>Local-first</h3><p>Notas e preferências ficam no navegador.</p></div><div><Icon name="Smartphone"/><h3>Responsivo</h3><p>Construído pensando primeiro no celular.</p></div></div></section>}

function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/>{<Route path="/tool/password" element={<Password/>}/>}<Route path="/tool/units" element={<Units/>}/><Route path="/tool/counter" element={<Counter/>}/><Route path="/tool/qr" element={<QR/>}/><Route path="/tool/timer" element={<Timer/>}/><Route path="/tool/notes" element={<Notes/>}/><Route path="/tool/calc" element={<Calc/>}/><Route path="/tool/colors" element={<Colors/>}/><Route path="/tool/currency" element={<Currency/>}/><Route path="/tool/text" element={<TextTool/>}/><Route path="/tool/video" element={<Media/>}/><Route path="/tool/audio" element={<Media audio/>}/></Routes></Layout>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);